# --- ПАМЯТЬ И ОЧИСТКА ---

# Максимальный объем RAM, который может занять Redis.
# Укажите примерно 70-80% от всей оперативной памяти сервера.
# У нас максимум 80+ человек полезут за логами
# Один человек в час путь генерирует максимум 10МБ логов
# Получаем 80 человек * 8 часовой день * 10МБ * == 6400МБ ~= 6.4ГБ
# Это верняя оценка, т.к. люди не играют так много и далеко не все
maxmemory 4gb

# Политика удаления: выкидывать самые старые (неиспользуемые) ключи,
# когда память заполнится до лимита.
maxmemory-policy allkeys-lru

# Сколько ключей Redis проверяет за раз при очистке (5 — стандарт, 10 — быстрее, но чуть больше нагрузка)
maxmemory-samples 5


# --- СЕТЬ И БЕЗОПАСНОСТЬ ---

# На каком порту слушать (стандарт 6379)
port 6379
# К каким IP разрешен доступ (127.0.0.1 — только локально)
# bind 127.0.0.1
# Слушать на всех интерфейсах (чтобы был доступ по локальному IP)
bind 0.0.0.0
# Выключаем защищенный режим, так как мы открыли bind
protected-mode no

# Пароль для доступа (обязательно, если Redis доступен извне)
requirepass UseRedisOnlyInDevEnv_2026

# --- ОТКЛЮЧЕНИЕ СОХРАНЕНИЯ (БЕЗ ДИСКА) ---

# Удаляем все стандартные точки сохранения в RDB
save ""

# Выключаем Append Only Mode (AOF)
appendonly no

# --- ОБЩИЕ НАСТРОЙКИ ---

# Запускать как фоновый процесс (yes для Linux серверов)
daemonize yes

# Путь к лог-файлу
logfile /var/log/redis/redis-server.log

# Количество баз данных (по умолчанию 16)
databases 16
